// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Interest struct {
	ID           int32
	InterestName string
	InterestImg  string
	Updatedat    sql.NullTime
}

type Place struct {
	ID           int32
	PlaceName    string
	Location     string
	LocationName string
	PalceImg     string
	InterestID   int32
}

type Trip struct {
	ID         int32
	TripName   string
	Cost       int32
	Duration   int32
	StartDate  time.Time
	Status     int32
	Orgernizer int32
}

type TripMember struct {
	ID     int32
	TripID int32
	Member int32
}

type User struct {
	ID         int64
	Email      string
	Username   string
	Status     int32
	ProfilePic sql.NullString
	IsActive   int32
	Createdat  time.Time
	Updatedat  sql.NullTime
}
