// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Interest struct {
	ID           int32        `json:"id"`
	InterestName string       `json:"interestName"`
	InterestImg  string       `json:"interestImg"`
	Updatedat    sql.NullTime `json:"updatedat"`
}

type Place struct {
	ID           int32  `json:"id"`
	PlaceName    string `json:"placeName"`
	Location     string `json:"location"`
	LocationName string `json:"locationName"`
	PalceImg     string `json:"palceImg"`
	InterestID   int32  `json:"interestID"`
}

type Trip struct {
	ID         int32     `json:"id"`
	TripName   string    `json:"tripName"`
	Cost       int32     `json:"cost"`
	Duration   int32     `json:"duration"`
	StartDate  time.Time `json:"startDate"`
	Status     int32     `json:"status"`
	Orgernizer int32     `json:"orgernizer"`
}

type TripMember struct {
	ID     int32 `json:"id"`
	TripID int32 `json:"tripID"`
	Member int32 `json:"member"`
}

type User struct {
	ID         int64          `json:"id"`
	Email      string         `json:"email"`
	Username   string         `json:"username"`
	Status     int32          `json:"status"`
	ProfilePic sql.NullString `json:"profilePic"`
	IsActive   int32          `json:"isActive"`
	Createdat  time.Time      `json:"createdat"`
	Updatedat  sql.NullTime   `json:"updatedat"`
}
